### ISSUE TITLE
Multiple errors with krb

### ISSUE THREAD

**Issue by IDerr** [ryba-io/ryba-cluster#12]
Hi,
Just trying a fresh install of ryba-cluster ( yes at 4:30AM) and currently experiencing some issues with krb : 
A lot of issues due to config modifications in 9b22caf2c32f4e1bc320924d7be00485d6f47edc

Here with zookeeper, but having the same for hadoop_core etc...
![](http://i.imgur.com/N3Hghbc.png)

In  the code, we have something like this :
**ryba/zookeeper/server/install :** 
``` coffee
{zookeeper, hadoop_group, realm} = @config.ryba
krb5 = @config.krb5_client.admin[realm]
```
But in the config we have this :
``` coffee
'masson/core/krb5_client': {}
```
Should we fix that in each modules or just modify the config file ?

PS : Perhaps is it currently being done, just saw the commit in ryba ?
Thanks for the work :)

**Comment by wdavidw** [comment]
krb5_client wasn't required on all hosts and I tend to depraciate the use of "implicit". I just fixed it, you can pull ryba-cluster with the changes

**Comment by IDerr** [comment]
Ok, thanks David
